#!/bin/bash

#
# Deb package formation for qgit
#
package_dir=$script_dir/build/${build_subdir}/deb/qgit
echo -e "\npackage_dir: $package_dir"

package_name="qgit-${full_package_vers}-${os_id}${os_ver}-${os_arch}.deb"
echo "package_name: $package_name"

rm -rf $package_dir

mkdir -p $package_dir/DEBIAN
mkdir -p $package_dir/usr/bin
mkdir -p $package_dir/usr/share/applications
mkdir -p $package_dir/usr/share/icons/hicolor/48x48/apps

cp $script_dir/setup/deb/qgit/DEBIAN/*  $package_dir/DEBIAN
cp $script_dir/qgit.desktop             $package_dir/usr/share/applications
cp $script_dir/src/resources/qgit.png   $package_dir/usr/share/icons/hicolor/48x48/apps
cp $build_dir/bin/qgit                  $package_dir/usr/bin

chmod -R go-w        $package_dir
chmod    u=rwx,go=rx $package_dir/DEBIAN/post*
#chmod   u=rwx,go=rx $package_dir/DEBIAN/pre*
chmod  u=rwx,go=rx   $package_dir/usr/bin/qgit

if [ "$build_mode" = "release" ]; then
    set +e
    echo "Removing debug info ... "
    for f in $(find $package_dir/usr/bin -type f); do strip_debug_info $f; done
    set -e
fi

# Packet size
installed_size=$(du -s $package_dir | sed -r 's/([0-9]+).*/\1/')
echo "installed_size: $installed_size"

packet_depends=$(cat <<-EOS
	libc6, libstdc++6, libqt5core5a, libqt5gui5, libqt5widgets5, git, \
	libhunspell-dev (>= 1.6.2)
EOS
)

os_arch_control=$os_arch
[ "${os_arch:0:3}" = "arm" ] && os_arch_control=armhf

sed -e "s/%VERSION%/${package_vers}-${package_date}git${gitrev}/" \
    -e "s/%ARCHITECTURE%/${os_arch_control}/" \
    -e "s/%INSTALLED_SIZE%/${installed_size}/" \
    -e "s/%DEPENDS%/${packet_depends}/" \
    -i $package_dir/DEBIAN/control

